# Clave única de tu proyecto en SonarQube
sonar.projectKey=correcciones

# Nombre opcional
sonar.projectName=Microservicio Inventario

# Versión opcional
sonar.projectVersion=1.0

# Directorio que contiene tu código fuente
sonar.sources=.

# Excluimos archivos SQL, archivos .txt, etc.
sonar.exclusions=**/*.sql,**/*.txt,venv/**

# Codificación de archivos
sonar.sourceEncoding=UTF-8

# URL de tu servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (reemplaza con tu token real)
sonar.login=sqp_392c6de4c9c8a287cfb73632c0ed0a7a2ad2861f

# Si tienes reporte de cobertura con Pytest/Coverage, p. ej.
# sonar.python.coverage.reportPaths=coverage.xml
