# Clave única de tu proyecto en SonarQube
sonar.projectKey=correcionus

# Nombre descriptivo (opcional)
sonar.projectName=Microservicio Usuarios

# Versión (opcional)
sonar.projectVersion=1.0

# Directorio donde están los archivos fuente
# "." indica la carpeta actual
sonar.sources=.

# Excluimos node_modules y archivos SQL del análisis:
sonar.exclusions=node_modules/**,**/*.sql

# URL de tu servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (cambia este valor por tu token real)
sonar.login=sqp_760ab03e31f2bed77488deb149d2bf298afe5b7d

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8

# (Opcional) Si tienes un reporte de cobertura con Jest u otra librería,
# podrías especificarlo así:
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
