sonar.projectKey=front
sonar.projectName=Frontend React/TypeScript
sonar.projectVersion=1.0

# Carpetas/archivos que analizaremos
sonar.sources=.
# Excluir node_modules y, opcionalmente, los archivos de test
sonar.exclusions=**/node_modules/**,**/*.test.tsx,**/*.spec.tsx

# Codificación
sonar.sourceEncoding=UTF-8

# URL y token de SonarQube
sonar.host.url=http://localhost:9000
sonar.login=sqp_7f7eb762b0acb58a0a0d18258cdf2ae3ab4125ed

# Reporte de cobertura (asumiendo que generas coverage/lcov.info con Jest o Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.typescript.lcov.reportPaths=coverage/lcov.info

